[package]
name = "neo4j_client"
version = "0.1.0"
authors = ["Peter Arato <it.arato@gmail.com>"]

[dependencies]
rustc-serialize = "0.3.16"
hyper = "0.10.4"
log = "0.3.4"

[dev-dependencies]
rand = "0.3.15"